extends Node

enum COMBAT_TARGET {PLAYER, ENEMY, ALL_ENEMIES}
enum COMBAT_ACTION_TYPE {BATTLE, EMPATHY}
enum AI_TYPE {BULLET, EMITTER}
enum ATTACK_RANGES {MELEE, RANGED}
enum STATS { HEARING, SIGHT, TOUCH, SMELL, TASTE, FAITH}
